// array de las cartas
const dataFromBD = [
    {
        id: "1",
        categoryId: "1",
        genero: "Ficción",
        titulo: "Nuestra parte de noche",
        autor:"Enriquez Mariana",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/671549.jpg",
        sinopsis: "PREMIO HERRALDE DE NOVELA 2019 Un padre y un hijo atraviesan Argentina por carretera; desde Buenos Aires hacia las cataratas de Iguazu; en la frontera norte con Brasil. Son los anos de la junta militar; hay controles de soldados armados y tension en el ambiente. El hijo se llama Gaspar y el padre trata de protegerlo del destino que le ha sido asignado. La madre murio en circunstancias poco claras; en un accidente que acaso no lo fue. Como su padre; Gaspar esta llamado a ser un medium en una sociedad secreta; la Orden; que contacta con la Oscuridad en busca de la vida eterna mediante atroces rituales. En ellos es vital disponer de un medium; pero el destino de estos seres dotados de poderes especiales es cruel; porque su desgaste fisico y mental es rapido e implacable. Los origenes de la Orden; regida por la poderosa familia de la madre de Gaspar; se remontan a siglos atras; cuando el conocimiento de la Oscuridad llego desde el corazon de africa a Inglaterra y desde alli se extendio hasta Argentina. El lector encontrara en estas paginas casas cuyo interior muta; pasadizos que esconden monstruos inimaginables; rituales con fieros y extaticos sacrificios humanos; andanzas en el Londres psicodelico de los anos sesenta; donde la madre de Gaspar conocio a un joven cantante de aire androgino llamado David; parpados humanos convertidos en fetiches; enigmaticas liturgias sexuales; la relacion entre padres e hijos; con la carga de una herencia atroz; y; de fondo; la represion de la dictadura militar; los desaparecidos y; mas adelante; la incierta llegada de la democracia; los primeros brotes del sida en Buenos Aires... El terror sobrenatural se entrecruza con terrores muy reales en esta novela perturbadora y deslumbrante; que consagra a Mariana Enriquez como una escritora fundamental de las letras latinoamericanas del siglo XXI.",
        precio: 4150.00,
        stock: 93,
    },
    {
        id: "2",
        categoryId: "1",
        titulo: "Personas decentes",
        genero: "Ficción",
        autor:"Padura Leonardo",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/697774.jpg",
        sinopsis: "La Habana; 2016. Varios acontecimientos históricos van a sacudir Cuba y poner patas arriba el ritmo de la isla: la visita de Barack Obama en lo que se ha llamado el «Deshielo cubano»; un concierto de los Rolling Stones y un desfile de Chanel. Por eso; cuando un exdirigente del Gobierno cubano aparece asesinado y mutilado en su departamento; la policía; desbordada por la visita presidencial; recurre a Mario Conde para que les dé una mano. Conde recordará que el muerto; un hombre déspota y cruel; había ejercido en el pasado de censor y extorsionado a los artistas para que no se desviaran de las consignas de la Revolución. Cuando unos días después se encuentre un segundo cadáver asesinado en parecidas circunstancias; sonarán todas las alarmas. Paralela a esa trama; se suma una historia situada un siglo antes; cuando La Habana era la Niza del Caribe y se vivía desenfrenadamente bajo la amenaza del cometa Halley. Para sorpresa de Mario Conde; presente y pasado tendrán unos vínculos insospechados.",
        precio: 4200.00,
        stock: 100,
    },
    {
        id: "3",
        categoryId: "1",
        titulo: "Violeta",
        genero: "Ficción",
        autor:"Isabel Allende",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/690814.jpg",
        sinopsis: "Violeta; la primera niña de una familia de cinco bulliciosos hermanos; viene al mundo un tormentoso día de 1920. Desde el principio su vida estará marcada por acontecimientos extraordinarios; pues todavía se sienten las ondas expansivas de la Gran Guerra cuando la gripe española llega a las orillas de su país sudamericano natal; casi en el momento exacto de su nacimiento. Gracias a la clarividencia del padre; la familia saldrá indemne de esta crisis para enfrentarse a una nueva; cuando la Gran Depresión altera la elegante vida urbana que Violeta ha conocido hasta ahora. Lo perderán todo y se verán obligados a retirarse a una región salvaje y remota del país. Allí Violeta alcanzará la mayoría de edad y tendrá su primer pretendiente... En una larga carta dirigida a una persona a la que ama por encima de todas las demás; Violeta rememora devastadores desengaños amorosos y romances apasionados; momentos de pobreza y también de prosperidad; pérdidas terribles e inmensas alegrías. Moldearán su vida algunos de los grandes sucesos de la historia: la lucha por los derechos de la mujer; el auge y la caída de tiranos y; en última instancia; no una sino dos pandemias. Vista con los ojos de una mujer poseedora de una pasión; una determinación y un sentido del humor inolvidables que la sostienen a lo largo de una vida turbulenta; Isabel Allende nos regala; una vez más; una historia épica profundamente inspiradora y emotiva.",
        precio: 4449.00,
        stock: 102,
    },
    {
        id: "4",
        categoryId: "2",
        titulo: "El poder de las palabras",
        genero: "No Ficción",
        autor:"Sigman Mariano",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/697635.jpg",
        sinopsis: "Nuestra mente es mucho más maleable de lo que creemos y; a pesar de que conservamos toda la vida la misma capacidad de aprender que tenemos de chicos; con el tiempo vamos perdiendo la necesidad y la motivación para hacerlo. Así; empezamos a convencernos de lo que no podemos: o somos malos para la matemática; o no nacimos para la música; o no podemos manejar nuestra ira; o nos es imposible superar el miedo. Este libro sostiene y demuestra que; independientemente del momento de nuestra existencia que atravesemos; podemos demoler esas creencias y cambiar ideas y sentimientos; aun aquellos más profundamente arraigados; aprendiendo a conversar. En efecto; la conversación -con otros y con nosotros- es la herramienta más extraordinaria para transformar nuestra vida. Después del éxito mundial de La vida secreta de la mente; Mariano Sigman reúne los avances más recientes de la neurociencia y los combina con historias de vida y una dosis importante de humor para explicar cómo y por qué las buenas conversaciones mejoran nuestras decisiones; ideas; memoria y emociones. He aquí un poder que está a nuestro alcance y podemos emplear para cambiar nuestra mente y tener una vida mejor: el poder de las palabras.",
        precio: 3499.00,
        stock: 78,
    },
    {
        id: "5",
        categoryId: "2",
        titulo: "Resetea tus intestinos",
        genero: "No Ficción",
        autor:"Pereyra Facundo",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/693797.jpg",
        sinopsis: "La mayoría de nosotros no sabe que los problemas digestivos causan estragos en todo el cuerpo: afecciones en la piel; cefaleas y migrañas; sobrepeso; enfermedades autoinmunes y la lista sigue... ¿Cómo recobrar la salud? El doctor Facundo Pereyra; especialista en medicina interna; gastroenterología y endoscopía digestiva; revela su método para resetear nuestros intestinos; sanar más de 15 enfermedades y recuperar nuestras ganas de vivir.",
        precio: 2750.00,
        stock: 67,
    },
    {
        id: "6",
        categoryId: "3",
        titulo: "BOULEVARD 1",
        genero: "Juveniles",
        autor:"Salvador Flor M.",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/691678.jpg",
        sinopsis: "Luke Howland; lleno de problemas y sumido en una desesperación profunda; y Hasley Weigel; tan despistada como optimista; no se ajustan al prototipo de pareja perfecta. Como si cada uno fuese un cielo; uno es tormenta y el otro; un día soleado: él es oscuridad. Ella; un rayo de sol. Y; sin embargo; juntos decidieron ponerle nombre a lo que habían creado: un boulevard teñido de tonos grisáceos y de azules celestes y eléctricos preparándose para la tormenta. Ella era para él y él era para ella. Los lectores dijeron: «Amé a Hasley; Luke y Neisan. Este libro es un boulevard de sueños rotos... literalmente». «No suelo llorar leyendo; pero esta vez ha sido inevitable». «Simplemente la historia más bonita que he leído nunca». «Ni todo el colirio del mundo puede rehidratarme los ojos después de tanto llorar». «Hay libros que marcan un antes y un después en la vida de cada lector; y este es el mío». «Es un libro precioso lleno de sentimientos y por encima de todo... de amor».",
        precio: 3049.00,
        stock: 87,
    },
    {
        id: "7",
        categoryId: "1",
        titulo: "La ciudad de las ranas",
        genero: "Ficción",
        autor: "Alconada Mon Hugo",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/697781.jpg",
        sinopsis: "La Argentina de fines del siglo XIX pujó entre el orden y el colapso, el progreso y las revoluciones mientras buscaba consolidar una identidad política.La fundación de La Plata en 1882 concentró, en ese contexto, las ilusiones y disputas de un grupo de hombres al que se conocería como la Generación del 80, aunque sus principales figuras no se veían a sí mismas como un bloque. Lucharon por el poder, se espiaron, tejieron acuerdos transitorios y conspiraron cada día, unos contra otros, en medio de una tensión social que amenazaba con arrasarlo todo.Este es el país que retrata de manera precisa y sutil La ciudad de las ranas, con personajes estelares: Julio Roca, su aliado y rival, Dardo Rocha, Eduardo Wilde y la jovencísima Guillermina de Oliveira Cézar, Miguel Juárez Celman, Ramón Falcón, católicos y masones, y los inmigrantes italianos, los grandes y anónimos protagonistas de la construcción de una ciudad llamada a ser referencia mundial.Entre esos inmigrantes, un muchacho llamado Íñigo Rocamora se erigió en líder. La urbe que nacía moldeó su destino, entre un amor improbable, la Masacre de San Ponciano, los prejuicios de la clase dominante y la Batalla de Ringuelet. Hugo Alconada Mon ha escrito una novela histórica apasionante y contundente.",
        precio: 4100.00,
        stock: 87,
    },
    {
        id: "8",
        categoryId: "1",
        titulo: "El hechizo del agua",
        genero: "Ficción",
        autor: "Bonelli Florencia",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/693343.jpg",
        sinopsis: "Brenda Gómez tiene una vida perfecta. Es una alumna destacada en la carrera de Ciencias Económicas, su novio es un joven ambicioso y con un gran futuro, sus amigas son leales, su familia la adora. Pero ella no es feliz. La domina un mundo interior complejo, plagado de sentimientos e ideas que oculta, porque la avergüenzan y la alejan del modelo que se impone seguir. De los secretos que esconde, uno la atormenta especialmente: ama a Diego Bertoni desde que tiene memoria; un amor extraño por varias razones, pero sobre todo un amor prohibido.",
        precio: 4200.00,
        stock: 67,
    },
    {
        id: "9",
        categoryId: "1",
        titulo: "Sarmiento",
        genero: "Ficción",
        autor: "Caparros Martin",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/697656.jpg",
        sinopsis: "«Ser presidente es una de esas extrañas cosas que conocen; desde el principio; su final: uno nunca sabe cuánto podrá durar un viaje; cuánto un amor; cuánto una enfermedad; pero el feliz desdichado al que sus compatriotas eligen para presidente sabe que; si un dios no lo remedia; dejará de serlo justo seis años después. Lo que no sabe es cuánto durarán esos seis años.» Al terminar el tramo culminante de su vida; Domingo Faustino Sarmiento repasa los episodios más públicos y los recodos más privados de su trayectoria. Humillado por la sordera; alza la voz. Habla de la muerte del hijo. Habla de esa pandemia que casi acaba con él. Habla de la guerra indeseada a la que no podía renunciar; de las relaciones clandestinas; del respeto inesperado por el antagonista; del desprecio por los que más se le parecen; de los abrazos siempre esquivos; de las derrotas del poder. La crítica dijo... «Caparrós es una manera de ver y entender el mundo.» Carles Geli; Babelia «Caparrós es colosal en esos terrenos resbaladizos donde las cosas dejan de encajar en los moldes correctos.» Leila Guerriero; Babelia «Es una obra rica y ambiciosa; una empresa arriesgada que debe ser conocida.» Juan Goytisolo «Caparrós provoca esa necesidad sonriente de subrayar; compartir en redes; reproducir sus trallazos.» Nadal Suau; El Cultural «Martín Caparrós no es de esos que te dicen lo que quieres escuchar. Sería más bien del campo contrario: esos que te tiran a la cara lo que rechazas y escondes.» Oriane Jeancourt; Transfuge",
        precio: 3999.00,
        stock: 63,
    },
    {
        id: "10",
        categoryId: "2",
        titulo: "El camino del artista",
        genero: "No Ficción",
        autor: "Cameron Julia",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/665254.jpg",
        sinopsis: "La mayoría de nosotros anhelamos ser más creativos y muchos creemos que conseguir serlo es imposible porque en realidad no lo somos. Este planteamiento es erróneo y lo único que provoca es que nuestra creatividad se quede dormida en nuestro interior junto a nuestra verdadera esencia. A menudo nos negamos el placer de soñar; de conseguir lo que siempre hemos deseado; de rechazar nuestros impulsos naturales; nuestra propia personalidad. El camino del artista nos enseña a crear con mayor libertad a través de la utilización consciente de una serie de herramientas que nos ayudarán a terminar con el bloqueo creativo. Su efecto es similar al yoga y la práctica constante de la escritura diaria -páginas matutinas-; los encuentros con el artista; el juego y una exhaustiva introspección guiada harán que modifiquemos nuestra conciencia y nos abramos a un nuevo horizonte imaginativo. Gracias a las enseñanzas de la reconocida escritora y artista Julia Cameron iniciaremos un camino creativo y espiritual que nos hará remontarnos a nuestra verdadera naturaleza; y en doce lecciones magistrales seremos capaces de rehabilitar nuestra creatividad; de entregarnos a la imaginación y encontrar el sentido de nuestra existencia. Un recorrido revelador por nuestras inseguridades y nuestros miedos; pero también por nuestros recuerdos; nuestros objetivos y por lo mejor de nosotros mismos. Una obra necesaria para escritores; poetas; actores; pintores; músicos o para cualquier otro individuo creativo. «La creatividad no tiene ni fondo ni techo aunque haya partes de su crecimiento que sean lentas. El ingrediente que se precisa es la fe -entendida como confianza férrea en uno mismo-. Este libro te muestra el camino y la fe necesarios para liberar la creatividad de las personas. Tómalo como un ejercicio para abrirte a una nueva perspectiva y libera al artista que llevas dentro». Julia Cameron",
        precio: 4199.00,
        stock: 77,
    },
    {
        id: "11",
        categoryId: "2",
        titulo: "Capitalimo y pulsion de muerte",
        genero: "No Ficción",
        autor: "Han Byung-Chul",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/697914.jpg",
        sinopsis: "Este libro reúne 14 artículos y 2 conversaciones de Byung-Chul Han acerca de la expansión del capitalismo y sus consecuencias. Lo que hoy llamamos «crecimiento» es en realidad la consecuencia de un aumento excesivo de carcinomas que destruyen el organismo social.",
        precio: 2270.00,
        stock: 55,
    },
    {
        id: "12",
        categoryId: "3",
        titulo: "BOULEVARD 2",
        genero: "Juveniles",
        autor: "Salvador Flor M.",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/696361.jpg",
        sinopsis: "El secreto de volver a empezar es darte otra oportunidad para ser feliz. El primer amor no se olvida; solo se supera y se aprende a vivir con su recuerdo. Hasley debe seguir con su vida; pasar página y mirar hacia adelante. Cuando su madre le dice que es hora de continuar y dejar el pasado atrás; esas palabras se le clavan como puñales en el alma. Ella es joven y tiene todo el tiempo del mundo para rehacer su vida. Una vida que está llena de oportunidades; aunque todavía no pueda verlas. Todo cobra un nuevo sentido con la aparición de Harry Beckinsale; licenciado en Derecho y unos años mayor que ella. ¿Será esta la nueva oportunidad para que sus sueños con Luke puedan descansar junto a su memoria? Los lectores han dicho... «Qué bonito acompañar a Hasley en su viaje de superación» «¿En algún momento se deja de llorar?» «Seguir adelante y que los recuerdos no duelan. Gracias; Flor; por esta lección» «El mejor cóctel de emociones habidas y por haber»",
        precio: 3049.00,
        stock: 43,
    },
    {
        id: "13",
        categoryId: "3",
        titulo: "Al final mueren los dos",
        genero: "Juveniles",
        autor: "Silvera Adam",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/646539.jpg",
        sinopsis: "Imagina un mundo en el que una organización les avisa a las personas la inminencia de su muerte. Imagina que empezó la cuenta regresiva. Imagina cómo vivirías tu vida en solo un día. ¿Estarías listo para decir adiós? Al final mueren los dos es un canto a la fuerza arrolladora de la vida; que transformará para siempre tu forma de comprender el tiempo; la amistad y el amor.",
        precio: 3490.00,
        stock: 61,
    },
    {
        id: "14",
        categoryId: "3",
        titulo: "El chico que dibujaba constelaciones",
        genero: "Juveniles",
        autor: "Kellen Alice",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/691015.jpg",
        sinopsis: "Esta es una historia de amor; de sueños y de vida. La de Valentina. La chica que no sabía que tenía el mundo a sus pies; la que creció y empezó a pensar en imposibles. La que cazaba estrellas; la que anhelaba más; la que tropezó con él. Con Gabriel. El chico que dibujaba constelaciones; el valiente e idealista; el que confió en las palabras «para siempre»; y creó los pilares que terminaron sosteniendo el pasado; el ahora; lo que fueron y los recuerdos que se convertirán en polvo. «Esta novela es lo más bonito que he podido leer en mucho tiempo. Me ha parecido un regalo; un soplo de vida... Y todo contado con tanta delicadeza que es precioso leerlo. Solo podría hacerlo Alice. Mil gracias por regalarnos a Valentina y a Gabriel; por su vida. No he podido ser más feliz leyéndolos»; Patricia Bejarano",
        precio: 3200.00,
        stock: 67,
    },
    {
        id: "15",
        categoryId: "3",
        titulo: "Bruja blanca, La asesino de brujas 1",
        genero: "Juveniles",
        autor: "Mahurin Shelby",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/681830.jpg",
        sinopsis: "«Un debut brillante; lleno de todo lo que me gusta: una heroína vibrante y completamente realizada; un sistema de magia intrincado y letal y un romance ardiente que me mantuvo en vilo toda la noche. Asesino de brujas: la bruja blanca es sin duda una joya.» ¿Sarah J. Maas; autora de la saga Una corte de espinas y rosas; best seller del New York Times. Unidos como uno para amarse; para honrarse o para arder. Dos años atrás; Louise le Blanc huyó de su aquelarre y se refugió en la ciudad de Cesarine; donde renunció a la magia para vivir de lo que pudiera robar. Allí; cazan a brujas como Lou. Les temen. Y las queman. Como cazador de la Iglesia; Reid Diggory ha vivido su vida bajo una regla: «No permitirás que ninguna bruja viva». Pero cuando Lou realiza una gran artimaña; tanto ella como Reid se ven obligados a aceptar una situación impensada: el matrimonio. Lou; incapaz de ignorar sus sentimientos que son cada vez más fuertes; pero sin poder cambiar quién es; Lou debe elegir. Asesino de brujas: la bruja blanca se desarrolla en un mundo de mujeres empoderadas; magia oscura y donde los romances son fuera de serie. Cuando lo termines de leer; querrás más.",
        precio: 3750.00,
        stock: 57,
    }
];

export default dataFromBD;