// array de las cartas
const dataFromBD = [
    {
        id: 1,
        genero: "Ficción",
        titulo: "Nuestra parte de noche",
        autor:"Enriquez Mariana",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/671549.jpg",
        sinopsis: "PREMIO HERRALDE DE NOVELA 2019 Un padre y un hijo atraviesan Argentina por carretera; desde Buenos Aires hacia las cataratas de Iguazu; en la frontera norte con Brasil. Son los anos de la junta militar; hay controles de soldados armados y tension en el ambiente. El hijo se llama Gaspar y el padre trata de protegerlo del destino que le ha sido asignado. La madre murio en circunstancias poco claras; en un accidente que acaso no lo fue. Como su padre; Gaspar esta llamado a ser un medium en una sociedad secreta; la Orden; que contacta con la Oscuridad en busca de la vida eterna mediante atroces rituales. En ellos es vital disponer de un medium; pero el destino de estos seres dotados de poderes especiales es cruel; porque su desgaste fisico y mental es rapido e implacable. Los origenes de la Orden; regida por la poderosa familia de la madre de Gaspar; se remontan a siglos atras; cuando el conocimiento de la Oscuridad llego desde el corazon de africa a Inglaterra y desde alli se extendio hasta Argentina. El lector encontrara en estas paginas casas cuyo interior muta; pasadizos que esconden monstruos inimaginables; rituales con fieros y extaticos sacrificios humanos; andanzas en el Londres psicodelico de los anos sesenta; donde la madre de Gaspar conocio a un joven cantante de aire androgino llamado David; parpados humanos convertidos en fetiches; enigmaticas liturgias sexuales; la relacion entre padres e hijos; con la carga de una herencia atroz; y; de fondo; la represion de la dictadura militar; los desaparecidos y; mas adelante; la incierta llegada de la democracia; los primeros brotes del sida en Buenos Aires... El terror sobrenatural se entrecruza con terrores muy reales en esta novela perturbadora y deslumbrante; que consagra a Mariana Enriquez como una escritora fundamental de las letras latinoamericanas del siglo XXI.",
        precio: "$4.150,00",
        stock: "5",
    },
    {
        id: 2,
        titulo: "Personas decentes",
        genero: "Ficción",
        autor:"Padura Leonardo",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/697774.jpg",
        sinopsis: "La Habana; 2016. Varios acontecimientos históricos van a sacudir Cuba y poner patas arriba el ritmo de la isla: la visita de Barack Obama en lo que se ha llamado el «Deshielo cubano»; un concierto de los Rolling Stones y un desfile de Chanel. Por eso; cuando un exdirigente del Gobierno cubano aparece asesinado y mutilado en su departamento; la policía; desbordada por la visita presidencial; recurre a Mario Conde para que les dé una mano. Conde recordará que el muerto; un hombre déspota y cruel; había ejercido en el pasado de censor y extorsionado a los artistas para que no se desviaran de las consignas de la Revolución. Cuando unos días después se encuentre un segundo cadáver asesinado en parecidas circunstancias; sonarán todas las alarmas. Paralela a esa trama; se suma una historia situada un siglo antes; cuando La Habana era la Niza del Caribe y se vivía desenfrenadamente bajo la amenaza del cometa Halley. Para sorpresa de Mario Conde; presente y pasado tendrán unos vínculos insospechados.",
        precio: "$4.200,00",
        stock: "5",
    },
    {
        id: 3,
        titulo: "Violeta",
        genero: "Ficción",
        autor:"Isabel Allende",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/690814.jpg",
        sinopsis: "Violeta; la primera niña de una familia de cinco bulliciosos hermanos; viene al mundo un tormentoso día de 1920. Desde el principio su vida estará marcada por acontecimientos extraordinarios; pues todavía se sienten las ondas expansivas de la Gran Guerra cuando la gripe española llega a las orillas de su país sudamericano natal; casi en el momento exacto de su nacimiento. Gracias a la clarividencia del padre; la familia saldrá indemne de esta crisis para enfrentarse a una nueva; cuando la Gran Depresión altera la elegante vida urbana que Violeta ha conocido hasta ahora. Lo perderán todo y se verán obligados a retirarse a una región salvaje y remota del país. Allí Violeta alcanzará la mayoría de edad y tendrá su primer pretendiente... En una larga carta dirigida a una persona a la que ama por encima de todas las demás; Violeta rememora devastadores desengaños amorosos y romances apasionados; momentos de pobreza y también de prosperidad; pérdidas terribles e inmensas alegrías. Moldearán su vida algunos de los grandes sucesos de la historia: la lucha por los derechos de la mujer; el auge y la caída de tiranos y; en última instancia; no una sino dos pandemias. Vista con los ojos de una mujer poseedora de una pasión; una determinación y un sentido del humor inolvidables que la sostienen a lo largo de una vida turbulenta; Isabel Allende nos regala; una vez más; una historia épica profundamente inspiradora y emotiva.",
        precio: "$4.449,00",
        stock: "5",
    },
    {
        id: 4,
        titulo: "El poder de las palabras",
        genero: "No Ficción",
        autor:"Sigman Mariano",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/697635.jpg",
        sinopsis: "Nuestra mente es mucho más maleable de lo que creemos y; a pesar de que conservamos toda la vida la misma capacidad de aprender que tenemos de chicos; con el tiempo vamos perdiendo la necesidad y la motivación para hacerlo. Así; empezamos a convencernos de lo que no podemos: o somos malos para la matemática; o no nacimos para la música; o no podemos manejar nuestra ira; o nos es imposible superar el miedo. Este libro sostiene y demuestra que; independientemente del momento de nuestra existencia que atravesemos; podemos demoler esas creencias y cambiar ideas y sentimientos; aun aquellos más profundamente arraigados; aprendiendo a conversar. En efecto; la conversación -con otros y con nosotros- es la herramienta más extraordinaria para transformar nuestra vida. Después del éxito mundial de La vida secreta de la mente; Mariano Sigman reúne los avances más recientes de la neurociencia y los combina con historias de vida y una dosis importante de humor para explicar cómo y por qué las buenas conversaciones mejoran nuestras decisiones; ideas; memoria y emociones. He aquí un poder que está a nuestro alcance y podemos emplear para cambiar nuestra mente y tener una vida mejor: el poder de las palabras.",
        precio: "$3.499,00",
        stock: "5",
    },
    {
        id: 5,
        titulo: "Resetea tus intestinos",
        genero: "No Ficción",
        autor:"Pereyra Facundo",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/693797.jpg",
        sinopsis: "La mayoría de nosotros no sabe que los problemas digestivos causan estragos en todo el cuerpo: afecciones en la piel; cefaleas y migrañas; sobrepeso; enfermedades autoinmunes y la lista sigue... ¿Cómo recobrar la salud? El doctor Facundo Pereyra; especialista en medicina interna; gastroenterología y endoscopía digestiva; revela su método para resetear nuestros intestinos; sanar más de 15 enfermedades y recuperar nuestras ganas de vivir.",
        precio: "$2.750,00",
        stock: "5",
    },
    {
        id: 6,
        titulo: "BOULEVARD 1",
        genero: "Juveniles",
        autor:"Salvador Flor M.",
        img: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/691678.jpg",
        sinopsis: "Luke Howland; lleno de problemas y sumido en una desesperación profunda; y Hasley Weigel; tan despistada como optimista; no se ajustan al prototipo de pareja perfecta. Como si cada uno fuese un cielo; uno es tormenta y el otro; un día soleado: él es oscuridad. Ella; un rayo de sol. Y; sin embargo; juntos decidieron ponerle nombre a lo que habían creado: un boulevard teñido de tonos grisáceos y de azules celestes y eléctricos preparándose para la tormenta. Ella era para él y él era para ella. Los lectores dijeron: «Amé a Hasley; Luke y Neisan. Este libro es un boulevard de sueños rotos... literalmente». «No suelo llorar leyendo; pero esta vez ha sido inevitable». «Simplemente la historia más bonita que he leído nunca». «Ni todo el colirio del mundo puede rehidratarme los ojos después de tanto llorar». «Hay libros que marcan un antes y un después en la vida de cada lector; y este es el mío». «Es un libro precioso lleno de sentimientos y por encima de todo... de amor».",
        precio: "$3.049,00",
        stock: "5",
    }
];

export default dataFromBD;